# Generated by Django 5.0.3 on 2024-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="newsBit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("channel", models.CharField(max_length=50)),
                ("transcript", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("publication_date", models.DateTimeField()),
                ("video_url", models.URLField()),
                ("image", models.URLField()),
                ("guid", models.CharField(max_length=50)),
            ],
        ),
    ]
