# Generated by Django 5.0.3 on 2024-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newsbit_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsbit",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
